version: '3.1'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
  kafka:
    image: debezium/kafka:1.4
    ports:
      - '9092:9092'
    links:
      - 'zookeeper:zookeeper'
#  mysql:
#    image: debezium/example-mysql:1.4
#    ports:
#      - '3306:3306'
#    environment:
#      - MYSQL_ROOT_PASSWORD=debezium
#      - MYSQL_USER=mysqluser
#      - MYSQL_PASSWORD=mysqlpw
