version: '3.1'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
  kafka:
    image: debezium/kafka:1.4
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181/kafka
  mysql:
    image: debezium/example-mysql:1.4
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  debezium-connect:
    image: debezium/connect:1.4
    ports:
      - '8083:8083'
    depends_on:
      - zookeeper
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
